version: '3.9'
services:
  pgserver:
    container_name: pgserver
    image: postgres:15
    networks:
      - myNetwork
    ports:
      - "5555:5432"
    volumes:
      - D:\tmp\todolist-docker\data:/var/lib/postgresql/data
      - D:\tmp\todolist-docker\sql:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  springboot-docker:
    container_name: springboot-docker
    image: testtodo-docker
    networks:
      - myNetwork
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      pgserver:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgserver:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
networks:
  myNetwork: